language: node_js

node_js:
    - '0.10'

# before_install:
#     - echo "$(date +%H:%M:%S.%N) - before_install begin"
#     - curl -O http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
#     - java -jar selenium-server-standalone-2.39.0.jar &
#     - sleep 10
#     - echo "$(date +%H:%M:%S.%N) - before_install end"

before_script:
    #- sudo npm install - is automatically executed when install is missing
    - node app.js &

#script:
#    - echo "$(date +%H:%M:%S.%N) - script begin"
#    - mocha --reporter spec

addons:
  sauce_connect: true

env:
  global:
    - secure: "EvQvxbIQRYDF2NvRDlC8tLeoKabuhi9D+d9y89jsVniyAkMd6HXzU6N+/rsKWnLSYg4fDzadHvXUN+ge9BP1JwMFsH1OOCifBCQQLfnrZQ1phnQEhwl8LDQHVZbRv9Wsk474+NcGkGiDOrjUjbadR6YCrisPt3CHAB1XQw4zIzE="
    - secure: "sAGCSM9rCbANjWeeLnF8i2y450c4EPGUuhlOeFCxnlisduDkiQ6sZgusOlL2NiPQwmHTCcVNn7reBcuUGg1NZJfRt4NMju9OtqzS/JLk2RW9+J3zUkDrx5tQhaivWlThakRAIpNeHpCBEL9tWk68pDZw+Bfc1e1Jh4H3ji91KtI="

  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Windows 8"
      _VERSION: "31"
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "26"
