language: node_js

node_js:
    - '0.10'

before_install:
    # download and start selenium server - thought that it is not necessary, but without the website is not available within SauceLabs.
    - echo "$(date +%H:%M:%S.%N) - before_install begin"
    # download selenium server
    - curl -O http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
    # start this before installation to let the server be up and ready without extra waiting time.
    - java -jar selenium-server-standalone-2.39.0.jar -Dwebdriver.chrome.driver=./chromedriver &
    # install phantomjs, too:
    - echo "$(date +%H:%M:%S.%N) - before_install end"


before_script:
    #- sudo npm install - is automatically executed when install is missing
    # node app.js is started in postinstall of npm install
    # - node app.js &
    # check that the web app is running:
    - wget http://localhost:3000/authors || true
    # show the beginning of the file - the whole file is not displayed within TRAVIS (because line is too long?)
    - cat authors | cut -d'/' -f1

script:
# automatically runs `npm test` - therefore the call to mocha is located in package.json
    - echo "$(date +%H:%M:%S.%N) - script begin"
    #- mocha --reporter spec
    #- export TEST_RUN_LOCAL=true && npm test
    #- echo "Run the same tests as above, but using the remote browser."
    - export TEST_RUN_LOCAL=false && npm test

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=christian_bromann
    - SAUCE_ACCESS_KEY=76eb06d5-252b-4e14-b67b-af4f30ff882c

  matrix:
#     - _BROWSER: "chrome"
#       _PLATFORM: "Windows 7"
#       _VERSION: "31"
#     - _BROWSER: "chrome"
#       _PLATFORM: "Windows 8"
#       _VERSION: "31"
#     - _BROWSER: "firefox"
#       _PLATFORM: "Linux"
#       _VERSION: "26"
    - _BROWSER: "chrome"
      _PLATFORM: "Linux"
      _VERSION: "30"
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "25"
